#!/usr/bin/python3
from math import gcd
holder = []
fileOpen = open('factors', 'r')
data = fileOpen.readlines()
temp = ([s.replace('\n', '') for s in data])
fileOpen.close
for place in data:
    holder.append(int(place))
# up till here i have moved the file content into an integer list.
holder.sort()
for place in holder:
    first, second, i = holder[0], place, 0
    while first < second:
        i += 1
        if place % i == 0:
            first = i
            second = place//first
            print(f"{place}:{first}*{second}")
            break
